### ISSUE TITLE
Issue when setting color of text

### ISSUE THREAD

**Issue by LaurenzV** [linebender/parley#100]
Hello,

first, thanks for creating this library, it seems to work really great so far! For context, I'm trying to use this library as a way to allow users to write formatted text to a PDF file with the crate I'm working on, and integrating `parley` was easier than I expected! But I'm facing some problem when writing colored text, and I'm not sure whether I'm misusing the API or whether something else is wrong. Consider the following example, which I adapted from `examples` and hopefully makes it easier to reproduce:

```
use parley::{FontContext, Layout, LayoutContext};
use parley::layout::{Alignment, PositionedLayoutItem};
use peniko::Color;
use parley::style::{FontFamily, FontStack, StyleProperty};

fn main() {
    let text = String::from(
        "Some test",
    );
    let display_scale = 1.0;

    let max_advance = Some(200.0 * display_scale);

    let text_color = Color::rgb8(255, 0, 0);

    let mut font_cx = FontContext::default();
    let mut layout_cx = LayoutContext::new();

    let mut builder = layout_cx.ranged_builder(&mut font_cx, &text, display_scale);

    let brush_style = StyleProperty::Brush(text_color);
    builder.push_default(&brush_style);

    let font_stack = FontStack::List(&[
        FontFamily::Named("Noto Sans"),
        FontFamily::Named("Noto Sans Arabic"),
        FontFamily::Named("Noto Color Emoji"),
    ]);
    let font_stack_style = StyleProperty::FontStack(font_stack);
    builder.push_default(&font_stack_style);
    builder.push_default(&StyleProperty::LineHeight(1.3));
    builder.push_default(&StyleProperty::FontSize(16.0));

    // let color_style = StyleProperty::Brush(Color::rgb8(0, 255, 0 ));
    // builder.push(&color_style, 5..8);

    let mut layout: Layout<Color> = builder.build();

    layout.break_all_lines(max_advance);
    layout.align(max_advance, Alignment::Start);

    for line in layout.lines() {
        for item in line.items() {
            match item {
                PositionedLayoutItem::GlyphRun(glyph_run) => {
                    let run = glyph_run.run();

                    for cluster in run.visual_clusters() {
                        for glyph in cluster.glyphs() {
                            println!("{:?}", glyph);
                        }
                    }
                }
                PositionedLayoutItem::InlineBox(_) => {}
            }
        }
    }
}
```

Once I run this,  the output is as expected:

```
Glyph { id: 54, style_index: 0, x: 0.0, y: 0.0, advance: 8.784 }
Glyph { id: 82, style_index: 0, x: 0.0, y: 0.0, advance: 9.68 }
Glyph { id: 80, style_index: 0, x: 0.0, y: 0.0, advance: 14.960001 }
Glyph { id: 72, style_index: 0, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 3, style_index: 0, x: 0.0, y: 0.0, advance: 4.1600003 }
Glyph { id: 87, style_index: 0, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 72, style_index: 0, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 86, style_index: 0, x: 0.0, y: 0.0, advance: 7.6640005 }
Glyph { id: 87, style_index: 0, x: 0.0, y: 0.0, advance: 5.7760005 }
```

And it looks fine in my PDF too:
<img width="225" alt="image" src="https://github.com/user-attachments/assets/bcd66dc2-9c8b-4104-9f11-b3520d847682">

Now I'm trying to make some characters green by uncommenting the following lines:
```
    // let color_style = StyleProperty::Brush(Color::rgb8(0, 255, 0 ));
    // builder.push(&color_style, 5..8);
```

But suddenly, the glyphs are more or less duplicated:
```
Glyph { id: 54, style_index: 0, x: 0.0, y: 0.0, advance: 8.784 }
Glyph { id: 82, style_index: 0, x: 0.0, y: 0.0, advance: 9.68 }
Glyph { id: 80, style_index: 0, x: 0.0, y: 0.0, advance: 14.960001 }
Glyph { id: 72, style_index: 0, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 3, style_index: 0, x: 0.0, y: 0.0, advance: 4.1600003 }
Glyph { id: 87, style_index: 1, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 72, style_index: 1, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 86, style_index: 1, x: 0.0, y: 0.0, advance: 7.6640005 }
Glyph { id: 87, style_index: 2, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 54, style_index: 0, x: 0.0, y: 0.0, advance: 8.784 }
Glyph { id: 82, style_index: 0, x: 0.0, y: 0.0, advance: 9.68 }
Glyph { id: 80, style_index: 0, x: 0.0, y: 0.0, advance: 14.960001 }
Glyph { id: 72, style_index: 0, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 3, style_index: 0, x: 0.0, y: 0.0, advance: 4.1600003 }
Glyph { id: 87, style_index: 1, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 72, style_index: 1, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 86, style_index: 1, x: 0.0, y: 0.0, advance: 7.6640005 }
Glyph { id: 87, style_index: 2, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 54, style_index: 0, x: 0.0, y: 0.0, advance: 8.784 }
Glyph { id: 82, style_index: 0, x: 0.0, y: 0.0, advance: 9.68 }
Glyph { id: 80, style_index: 0, x: 0.0, y: 0.0, advance: 14.960001 }
Glyph { id: 72, style_index: 0, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 3, style_index: 0, x: 0.0, y: 0.0, advance: 4.1600003 }
Glyph { id: 87, style_index: 1, x: 0.0, y: 0.0, advance: 5.7760005 }
Glyph { id: 72, style_index: 1, x: 0.0, y: 0.0, advance: 9.024 }
Glyph { id: 86, style_index: 1, x: 0.0, y: 0.0, advance: 7.6640005 }
Glyph { id: 87, style_index: 2, x: 0.0, y: 0.0, advance: 5.7760005 }
```

This is how it looks with my PDF rendering:
<img width="335" alt="image" src="https://github.com/user-attachments/assets/0bb76bc8-851f-4393-a142-cf5187c3e859">

Am I doing something wrong or is there some other issue going on?

**Comment by dfrg** [comment]
This seems very wrong and I don’t see any issues with your code. Given the presence of inline box, I’m assuming you’re using the code from git. Can you try with the version on crates.io and see if it exhibits the same problem? I’d like to narrow down whether this is an old bug or something introduced with inline boxes.

**Comment by LaurenzV** [comment]
Yes, I'm using the `git` version. I'll give it a try!

**Comment by dfrg** [comment]
I take that back… you’re taking the outer `Run` from `GlyphRun` and iterating over the glyphs in all the clusters which will yield duplicates. You need to call `glyphs()` (or `positioned_glyphs()`) on `glyph_run` to get the proper styled subset.

**Comment by LaurenzV** [comment]
Yes, looks like the issue disappears if I iterate over the glyphs directly. Is there no way to do it via clusters though? :( The problem is that I do need the cluster information so that I can get the corresponding text of the cluster, to ensure that text selection works properly in the PDF.

**Comment by dfrg** [comment]
The intention is that the `Cursor` type would be used for text selection separately from rendering. If you’re trying to extract all of the positioned layout information into a separate data structure I think that’s going to be complicated with the current API but it’s potentially something we can support.

**Comment by LaurenzV** [comment]
Alright, now I understand what's going on. So basically, what I want is  `glyph_run` to have a `clusters`/`visual_clusters` method, like `Run` does. 

From what I can see, a `GlyphRun` basically stores the index of the start glyph as well as the number of glyphs that are part of the run. And once we call `glyphs`, we flat map the glyphs from all clusters of the `Run` and return the glyphs that are part of that specific `GlyphRun`:


```rs
/// Returns an iterator over the glyphs in the run.
    pub fn glyphs(&'a self) -> impl Iterator<Item = Glyph> + 'a + Clone {
        self.run
            .visual_clusters()
            .flat_map(|cluster| cluster.glyphs())
            .skip(self.glyph_start)
            .take(self.glyph_count)
    }
```

From my understanding, a cluster is always an "unbreakable" sequence of glyphs, does that mean that `self.glyph_start` always refers to the first glyph in a cluster, and `self.glyph_count` will always end with the last glyph of a cluster? So are the glyphs returned by this method _always_ part of one/multiple full clusters? If so, shouldn't it be possible to adapt this method so that it returns the clusters that are covered by `self.glyph_start` and `self.glyph_count`?

**Comment by dfrg** [comment]
Right, glyph runs can break clusters if the individual glyphs have different styles (there's a `DIVERGENT_STYLES` flag in there somewhere). At the point of rendering, we don't care about clusters anymore but we do try to honor individual styles if possible. For example, having different colors on a base character and its associated mark. Of course, as I'm sure you're aware, normalization and various OpenType features can compose these, so it's dependent on the font.

**Comment by LaurenzV** [comment]
Got it, I will have to figure out something else then. Thanks anyway!

**Comment by DJMcNab** [comment]
We're going to need to do the same thing in Masonry for selecting text; currently it's based on the glyphs, whereas we also need to make it be based on the clusters. It's not been a priority yet, though.

**Comment by dfrg** [comment]
For visual selection geometry, we essentially need to port https://github.com/dfrg/swash_demo/blob/55aedbc8604201f1b4925e2b986db59b838dc062/src/layout/nav.rs#L295 to parley.
