### ISSUE TITLE
`swash_render` not rendering on `main`

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/parley#114]
@dfrg In 14070d547913e407abf8c7cad2d5ca7fcd00cb59 (PR #106), you had this in your changes:

```diff
--- a/examples/swash_render/src/main.rs
+++ b/examples/swash_render/src/main.rs
@@ -80,7 +80,6 @@ fn main() {
     let mut layout: Layout<Color> = builder.build();

     // Perform layout (including bidi resolution and shaping) with start alignment
-    layout.break_all_lines(max_advance);
     layout.align(max_advance, Alignment::Start);

     // Create image to render into
```

That wasn't done to the `tiny_skia_render` example and after this commit, the `tiny_skia_render` example still renders, but the `swash_render` does not.

Restoring this line appears to let things still work...

Should this line be added back in? Should something else be fixed? Should the `tiny_skia_render` example be updated in some similar way if this change remains in place?

**Comment by waywardmonkeys** [comment]
I found this while trying to validate that https://github.com/dfrg/swash/pull/61 didn't break anything...

**Comment by nicoburns** [comment]
> Should this line be added back in? 

I'm pretty sure it should. I'm surprised CI didn't catch this!

**Comment by waywardmonkeys** [comment]
I'll submit a PR for it shortly.
