### ISSUE TITLE
PlainEditor: make relayout lazy

### ISSUE THREAD

**Issue by nicoburns** [linebender/parley#134]
Rather than eagerly rebuilding the layout when some change invalidates it we should consider setting a dirty flag and relayout lazily when we require an accurate layout.

This would allow multiple changes to be applied without rebuilding the layout multiple times.

**Comment by xorgy** [comment]
Sure, this is sort of happening right now, but it's not rigorous so there might be some unnecessary layout. Layout is dirty for Selection construction (both index and point) when the buffer contents or width change.

**Comment by nicoburns** [comment]
Implemented in https://github.com/linebender/parley/pull/192
