### ISSUE TITLE
`Arc<str>` in `PlainEditor`?

### ISSUE THREAD

**Issue by mwcampbell** [linebender/parley#150]
Are we sure we want to use `Arc<str>` in `PlainEditor`, for `PlainEditor::text` and for a couple of the `PlainEditorOp` variants? It seems to me that it would be unequivocally better for `PlainEditor::text` to return `&str`; having it clone into an `Arc<str>` just seems like an unforced pessimization. Using `&str` for `PlainEditorOp` variants would, of course, require that enum to have a lifetime parameter, but might still be worth it.

**Comment by nicoburns** [comment]
I very much agree. I also think that if an owned type is desired then `String` would be better than `Arc<str>`.

**Comment by mwcampbell** [comment]
Fixed by #154
