### ISSUE TITLE
Italic CascadiaCove Nerd Font is loaded completely wrong

### ISSUE THREAD

**Issue by fredizzimo** [linebender/parley#95]
`StyleProperty::FontStack(FontStack::Source("CaskaydiaCove Nerd Font" ))`
`StyleProperty::FontStyle(FontStyle::Italic)`

Loads as semilight with embolden set to true: `CaskaydiaCove NF SemiLight Italic`, but `CaskaydiaCove NF Italic` should be loaded, which has the regular 400 weight, and does not need embolden.

So, this is like a combination of:
* https://github.com/linebender/parley/issues/92
* https://github.com/linebender/parley/issues/93

But in this case embolden is actually set, although a boolean is not very useful for this case, since if no 400 weight was available, it would only need to embolden 50 units, or almost nothing. Compared to almost doubling the weight to make it bold.

OS: Linux

**Comment by dfrg** [comment]
Hazarding a guess, this might have to do with the transform fontconfig applies in attempt to fit all fonts into the RBIZ model. We do try to undo this to achieve proper family grouping but it’s likely that some patterns have been missed leading to poor matching.

**Comment by nicoburns** [comment]
> RBIZ model

For anyone else wondering what this is it's:

- R - Regular
- B - Bold
- I  - Italic
- Z - Bold Italic

And the idea that these are the only 4 font variants (that fits neatly with the typical boolean Bold and Italic buttons in word processors)
